//
// Autogenerated by Thrift Compiler (0.9.1)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var Thrift = require('thrift').Thrift;

var ttypes = require('./metaq_types');
//HELPER FUNCTIONS AND STRUCTURES

MetaqService_sendMsg_args = function(args) {
  this.jsonMsg = null;
  if (args) {
    if (args.jsonMsg !== undefined) {
      this.jsonMsg = args.jsonMsg;
    }
  }
};
MetaqService_sendMsg_args.prototype = {};
MetaqService_sendMsg_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.jsonMsg = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

MetaqService_sendMsg_args.prototype.write = function(output) {
  output.writeStructBegin('MetaqService_sendMsg_args');
  if (this.jsonMsg !== null && this.jsonMsg !== undefined) {
    output.writeFieldBegin('jsonMsg', Thrift.Type.STRING, 1);
    output.writeString(this.jsonMsg);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

MetaqService_sendMsg_result = function(args) {
  this.success = null;
  this.ex = null;
  if (args instanceof ttypes.SendFailException) {
    this.ex = args;
    return;
  }
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
    if (args.ex !== undefined) {
      this.ex = args.ex;
    }
  }
};
MetaqService_sendMsg_result.prototype = {};
MetaqService_sendMsg_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.BOOL) {
        this.success = input.readBool();
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.ex = new ttypes.SendFailException();
        this.ex.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

MetaqService_sendMsg_result.prototype.write = function(output) {
  output.writeStructBegin('MetaqService_sendMsg_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.BOOL, 0);
    output.writeBool(this.success);
    output.writeFieldEnd();
  }
  if (this.ex !== null && this.ex !== undefined) {
    output.writeFieldBegin('ex', Thrift.Type.STRUCT, 1);
    this.ex.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

MetaqServiceClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this.seqid = 0;
    this._reqs = {};
};
MetaqServiceClient.prototype = {};
MetaqServiceClient.prototype.sendMsg = function(jsonMsg, callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_sendMsg(jsonMsg);
};

MetaqServiceClient.prototype.send_sendMsg = function(jsonMsg) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('sendMsg', Thrift.MessageType.CALL, this.seqid);
  var args = new MetaqService_sendMsg_args();
  args.jsonMsg = jsonMsg;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

MetaqServiceClient.prototype.recv_sendMsg = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new MetaqService_sendMsg_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.ex) {
    return callback(result.ex);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('sendMsg failed: unknown result');
};
MetaqServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
MetaqServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.Exception, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

MetaqServiceProcessor.prototype.process_sendMsg = function(seqid, input, output) {
  var args = new MetaqService_sendMsg_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.sendMsg(args.jsonMsg, function (err, result) {
    var result = new MetaqService_sendMsg_result((err != null ? err : {success: result}));
    output.writeMessageBegin("sendMsg", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

